[package]
name = "dev_guide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "activity"
path = "src/activity/activitylib.rs"

[dependencies]
chrono = "0.4.24"
thiserror = "1.0"